### ISSUE TITLE
REM dev plan for Semarang

### ISSUE THREAD

**Issue by anexact** [urbanriskmap/riskmap#224]
FY17Ext Dev Meeting Field Office 15 _ MF & EH will confirm what district boundaries are available for Semarang before the end of August. Depending on interest from municipal and provincial BPBDs, we will propose REM development or simply public roll out; ET to discuss with TH longer strategy re: Central Java.

**Comment by fadmastuti** [comment]
Administrative boundary for Semarang (city) is available up to Kelurahan level on OSM. However, since the local communities and universities (students) are very strong, I think once they feel that PetaBencana/Semarang is useful, they will cooperate for completing the administrative boundaries up to the lower level or whichever they need. 

@talltom

**Comment by talltom** [comment]
Hi @anexact and @fadmastuti now that Semarang is in development (almost ready for production) I'm going to close this ticket until we have data available for development of REM.

Please also post REM related issues in https://github.com/urbanriskmap/cognicity-rem
