### ISSUE TITLE
Translate code to Angular

### ISSUE THREAD

**Issue by ojha-url** [urbanriskmap/riskmap#240]
- decision to be made based on support for integrated tests

**Comment by matthewberryman** [comment]
Support for tests is only one consideration. Vue is more light weight (hence faster learning curve) and flexible, etc.

**Comment by abrahamq** [comment]
My thoughts on Angular: 
Cons: 
1. Large learning curve
2. Creates a (slightly larger) bundle

Pros: 
1. Huge ecosystem- especially lots of e2e testing support using protractor.- this is something we can't currently do with aurelia and we are sorely missing it. We've tried 2 different ways of getting e2e testing but none of them have worked well or at all. Not even unit tests are currently working well in our Aurelia projects.
2. Lots of support because it's been out and used by large companies for a while. 
3. One right way to do a lot of things.
4. es6 with typescript 
5. Already used in another project (cognicity-rem-analysis)

I think that vue is not yet mature enough for us to use it in production.

**Comment by talltom** [comment]
@matthewberryman - provision for testing is our only cost/time incentive for switching frameworks at the moment (although it is a really big one, hence the discussion).

@abrahamq - I've spoken to couple of different devs over past few months, all agreed that it is a good framework and recommend using it. According to one metric I read it has as many users (based on Github activity I think) as Angular.

**Comment by abrahamq** [comment]
@talltom Looks like vue also has good e2e testing support: https://hackernoon.com/a-modern-way-to-do-e2e-testing-for-vue-js-apps-cebe0a07499c 

one thing I'm worried about is that there's many right ways of doing things in vue, which means more choices and more overhead?

I do agree that typescript is a huge hurdle

**Comment by talltom** [comment]
@abrahamq having just got everything to ES6/2015 I'll be really sad if we introduce a new thing. Client, server, Lambdas and even our testing framework for the schema are now in ES6 :)

regarding Vue.js I don't think its a magic bullet, but I've been polling quite a few people about it and seems a viable alternative to react which we already agreed we don't want to use.

**Comment by matthewberryman** [comment]
@abrahamq Having one right way to do things can mean less flexibility to get things done in a concise way, and a weightier framework can add more cognitive overhead just because it's bigger and more complex (i.e. the overhead is in the framework, not the overhead from your code doing things in different ways). Strong typing can be good (and I've seen some neat stuff in TypeScript) but it can also add overheads to code (casting) that sometimes outweigh the benefits. Plus JS programmers are easier to find than TS programmers.

**Comment by ojha-url** [comment]
@abrahamq , Aurelia just released some major changes to their core libs:
http://blog.aurelia.io/2017/10/03/aurelia-release-notes-early-october-2017/
which means they are actively developing it. 
Can you reach out to them explaining the issues that you are facing with e2e testing? 
This would be a great help in deciding upon the issue and can potentially avoid a total code overhaul.

**Comment by abrahamq** [comment]
Awesome, happy to do that. Can we time box it to 3 hrs? Might end up with no hair otherwise.

**Comment by abrahamq** [comment]
Looks like they've fixed some bugs in their protractor plugin which was a major issue: 

https://github.com/aurelia/protractor-plugin/blob/master/index.js

**Comment by talltom** [comment]
Angular version in progress: https://github.com/urbanriskmap/riskmap-ng
